version: "3"
services:
  host-server:
    build: ./server
    restart: always
    environment:
      PORT: 7080
  
  remote-server:
    build: ./server
    restart: always
    environment:
      PORT: 7080

  host-client:
    build: ./host-client
    restart: always

  remote-client:
    build: ./remote-client
    restart: always

  proxy:
    build: ./proxy
    restart: always
    environment:
      SERVER_URL: http://host-server:7080
      UI_URL: http://host-client
      REMOTE_UI_URL: http://remote-client
      REMOTE_SERVER_URL: http://remote-server:7080
    ports:
      - "80:80"
